name: CI KVM test caching

on:
  push:
    branches: [ "ci-kvm-caching" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update package cache
      run: sudo apt-get update -y
    - name: Install build and runtime dependencies
      run: sudo apt-get install -y bc gawk gcc git indent make sed flex bison libelf-dev udev ccache virtme-ng
    - run: echo "PATH=/usr/lib64/ccache:/usr/lib/ccache:$PATH" >> "$GITHUB_ENV"
    - run: echo "CCACHE_DIR=/home/runner/ccache" >> "$GITHUB_ENV"
    - run: ccache -s
    - name: Restore build ccache
      id: ccache-build
      uses: actions/cache@v5
      with:
        path: "/home/runner/ccache"
        key: kernel-build-ccache
    - run: ccache -s
    - run: type -p gcc
    - name: Build kernel
      run: |
        set -x
        ccache -s
        vng --verbose --kconfig
        make -j 4 kernel/
        ccache -s
