name: CI KVM test caching

on:
  push:
    branches: [ "ci-kvm-caching" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update package cache
      run: sudo apt-get update -y
    - name: Install build and runtime dependencies
      run: sudo apt-get install -y bc gawk gcc git indent make sed flex bison libelf-dev udev virtme-ng
    - name: Restore build cache
      id: cache-build
      uses: actions/cache@v5
      with:
        path: "/home/runner/build"
        key: kernel-build
    - name: Build kernel (optional)
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: |
        set -x
        vng --version
        mkdir -p /home/runner/build
        ls -laR /home/runner/build
        export KBUILD_OUTPUT=/home/runner/build
        vng --verbose --kconfig -- O=/home/runner/build
        #make -j 4 O=/home/runner/build kernel/
        #ls -laR /home/runner/build
